Smoke

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -244,18 +244,23 @@ jobs:
             npm install
             # Run and save the migration output
             npm run migrations > migrations_dump.txt
+            echo "~/project/backend/migrations_dump.txt"
+            cat ~/project/backend/migrations_dump.txt  
       - run:
           name: Send migration results to memstash
           command: |
             if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
             then
               curl -H "Content-Type: text/plain" -H "token: 7933fe63-4687-4fa1-8426-aa25aa1730ec" --request PUT --data "1" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
+            else 
+              echo "Migration failed."
+              exit 1
             fi
       # Rollback on failure      
       - revert-migrations:
-          workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"  
-      - destroy-environment:
-          workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"  
+          workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"
+#      - destroy-environment:
+#          workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"  
 #      - notify-on-failure
 
   deploy-frontend:
@@ -299,8 +304,8 @@ jobs:
       # Rollback on failure      
       - revert-migrations:
           workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"  
-      - destroy-environment:
-          workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"  
+#      - destroy-environment:
+#          workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"  
 #      - notify-on-failure
 
   deploy-backend:
@@ -330,10 +335,10 @@ jobs:
             cd .circleci/ansible
             ansible-playbook -i inventory.txt deploy-backend.yml
       # Rollback on failure      
-      - revert-migrations:
-          workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"  
-      - destroy-environment:
-          workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"  
+#      - revert-migrations:
+#          workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"  
+#      - destroy-environment:
+#          workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"  
 #      - notify-on-failure
 
   smoke-test:
@@ -378,10 +383,10 @@ jobs:
               return 1
             fi
       # Here's where you will add some code to rollback on failure  
-      - revert-migrations:
-          workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"  
-      - destroy-environment:
-          workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"  
+#      - revert-migrations:
+#          workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"  
+#      - destroy-environment:
+#          workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}"  
 #      - notify-on-failure
 
   cloudfront-update:
